parameters:
    env(UNZER_ENCRYPTION_KEY): 'def000002f45b81aa090e24a233d11e5b6348131bf27a28fdcae1972841dd98a565d678b144a13b880c88bbea36327126f9962a40b2e07d5258360ec44c30804fb011883'
    sylius_refund.supported_gateways:
        - offline
        - unzer_payment

sylius_grid:
    templates:
        action:
            enable_unzer: "@SyliusUnzerPlugin/PaymentMethod/Grid/Action/create.html.twig"
    grids:
        sylius_admin_payment_method:
            actions:
                main:
                    enable_unzer:
                        type: enable_unzer
sylius_twig_hooks:
    hooks:
        'sylius_shop.base#stylesheets':
            unzer_stylesheets:
                template: '@SyliusUnzerPlugin/Checkout/unzer_styles.html.twig'
                priority: 1
        'sylius_shop.base#javascripts':
            unzer_scripts:
                template: '@SyliusUnzerPlugin/Checkout/unzer_scripts.html.twig'
                priority: 1
        'sylius_unzer.admin.config':
            sidebar:
                template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
                priority: 200
            navbar:
                template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
                priority: 100
            content:
                template: '@SyliusAdmin/shared/crud/common/content.html.twig'
                priority: 0
        'sylius_shop.checkout.complete.content.form':
            unzer_payment_page_dialog:
                template: "@SyliusUnzerPlugin/Checkout/Complete/paymet_page_dialog.html.twig"
                priority: 1
        'sylius_unzer.admin.config.content':
            header:
                template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
                priority: 100
            body:
                template: '@SyliusUnzerPlugin/hooks/body.html.twig'
                priority: 0
        'sylius_shop.shared.form.select_payment.payment':
            choice:
                template: '@SyliusUnzerPlugin/hooks/checkout/choice.html.twig'
        'sylius_admin.order.show.content.sections.payments':
            unzer_payment_content:
                template: "@SyliusUnzerPlugin/Order/Show/_order.html.twig"
                priority: 100
        'sylius_shop.shared.order.show.summary.statuses.payments.list':
            method:
                template: "@SyliusUnzerPlugin/hooks/order/payments/list/method.html.twig"
                priority: 200
        'sylius_shop.order.show.content.form.select_payment.payment.unzer.shop.order.show.before_navigation':
            unzer_payment_page_dialog:
                 template: "@SyliusUnzerPlugin/Checkout/Complete/paymet_page_dialog.html.twig"
                 priority: 1
        'sylius_admin.order.show.content.sections.payments.item.actions':
            complete:                 
                    template: "@SyliusUnzerPlugin/Order/Show/Payment/_completeTransition.html.twig"
                    priority: 1

sylius_payment:
    resources:
        payment_method:
            classes:
                controller: SyliusUnzerPlugin\Controller\PaymentMethodController

monolog:
    channels: [ 'unzer' ]
    handlers:
        unzer:
            level: debug
            type: stream
            path: '%kernel.logs_dir%/unzer.log'
            channels: [ unzer ]
